### ISSUE TITLE
This is such a helpful repo! Thanks a lot for making it!

### ISSUE THREAD

**Issue by loneicewolf** [Daodavid93/Barnes-Hut-Algorithm_Nbodies_Problem#22]
Thanks!
I just needed to write this thank you word, this is super helpful.

**Comment by loneicewolf** [comment]
**this issue can be closed.** :) wishes from sweden!

**Comment by daodavid** [comment]
Thank you,
You are welcome to contribute :)

**Comment by loneicewolf** [comment]
If I find anything that can be improved, I'll happily make a *PR*, good day! 
^_^
